name: Budibase Release
concurrency: release

on:
  push:
    branches:
      - master
    paths:
      - ".aws/**"
      - ".github/**"
      - "charts/**"
      - "packages/**"
      - "scripts/**"
      - "package.json"
      - "yarn.lock"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:
    inputs:
      versioning:
        type: choice
        description: "Versioning type: patch, minor, major"
        default: patch
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          #          configuration: |
          #            {
          #              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
          #              "categories": [
          #                {
          #                    "title": "## 🚀 Features",
          #                    "labels": ["feature"]
          #                },
          #                {
          #                    "title": "## 🐛 Fixes",
          #                    "labels": ["fix"]
          #                },
          #                {
          #                    "title": "## 🧪 Tests",
          #                    "labels": ["test"]
          #                },
          #                {
          #                    "title": "## 💬 Other",
          #                    "labels": ["other"]
          #                },
          #                {
          #                    "title": "## 📦 Dependencies",
          #                    "labels": ["dependencies"]
          #                }
          #              ]
          #            }
          fromTag: "v2.1.33"
          toTag: "v2.1.40"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display notes
        run: echo "Release Notes ${{steps.github_release.outputs.changelog}}"
      - name: Outputs failed
        run: echo "Outputs failed? ${{steps.github_release.outputs.failed}}"

      - name: Changed files
        run: echo "Changed files ${{steps.github_release.outputs.changed_files}}"

      - name: Pull requests
        run: echo "Pull Requests ${{steps.github_release.outputs.pull_requests}}"

      - name: Commits
        run: echo "Commits ${{steps.github_release.outputs.commits}}"
